baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "NightlyDev"
theme = ['hugo-cloak-email', 'hello-friend-ng']

[params]
subtitle = "let's create something amazing"
homePageTitle = "Hey 👽, I'm Javier"
homeSubtitle = "let's create something amazing"
EnableThemeToggle = true

[[params.social]]
  name = "github"
  url  = "https://github.com/javiermgc"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/javiermgc"

[[params.social]]
  name = "email"
  url  = "mailto:javiermariagarciacuevas@gmail.com"


[languages.en.params.logo]
      logoText = "NightlyDev"


[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
[[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

[markup]
  [markup.highlight]
    noClasses = false